name: Deploy Azure Functions Backend
on:
    push:
        branches:
            - azureFunctionsBranch
    workflow_dispatch:

env:
    AZURE_FUNCTIONAPP_NAME: 'cne-functions'
    AZURE_FUNCTIONAPP_PACKAGE_PATH: './functions'
    NODE_VERSION: '22.x'

jobs:
    build-and-deploy-functions:
        runs-on: ubuntu-latest
        environment: dev

        steps:
            - name: checkout Repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install dependencies and build
              run: |
                  npm install
                  npm run clean --if-present
                  npm run build --if-present
              working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
            - name: Generate Prisma Client
              run: npx prisma generate
              working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

            - name: Deploy to Azure Functions
              uses: Azure/functions-action@v1
              with:
                  app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
                  package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
                  publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
